apiVersion: v1
kind: Pod

metadata:
  name: broken-config
  namespace: myk8s

spec:
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sh
        - -c
        - sleep 3600
      env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: does-not-exist
              key: APP_MESSAGE
