apiVersion: v1
kind: Pod

metadata:
  name: broken-secret
  namespace: myk8s

spec:
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sh
        - -c
        - sleep 3600
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: missing-secret
              key: DB_PASSWORD
