apiVersion: v1
kind: Pod

metadata:
  name: secret-reader
  namespace: myk8s

spec:
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sh
        - -c
        - sleep 3600
      volumeMounts:
        - name: app-secret
          mountPath: /etc/app-secret
          readOnly: true

  volumes:
    - name: app-secret
      secret:
        secretName: app-secret
