apiVersion: v1
kind: Pod

metadata:
  name: broken-storage
  namespace: myk8s

spec:
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sh
        - -c
        - sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: broken-pvc
