apiVersion: v1
kind: Pod

metadata:
  name: emptydir-demo
  namespace: myk8s

spec:
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sh
        - -c
        - sleep 3600
      volumeMounts:
        - name: demo-storage
          mountPath: /data

  volumes:
    - name: demo-storage
      emptyDir: {}
