apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: broken-pvc
  namespace: myk8s

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: standard

  resources:
    requests:
      storage: 100Mi
