apiVersion: v1
kind: Pod

metadata:
  name: pvc-demo
  namespace: myk8s

spec:
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sh
        - -c
        - sleep 3600
      volumeMounts:
        - name: persistent-storage
          mountPath: /data

  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: demo-pvc
